FROM node:lts-alpine AS builder
WORKDIR /app
RUN apk add --no-cache curl

EXPOSE 3000

CMD [ "sh", "-c", "npm install && npm run dev -- --host" ]

HEALTHCHECK CMD curl -f -o /dev/null http://localhost:3000
