FROM denoland/deno:alpine AS builder
RUN apk add --no-cache curl
WORKDIR /app

COPY package.json deno.lock .
RUN deno install --allow-scripts=npm:@tailwindcss/oxide@4.1.11
COPY svelte.config.js .
RUN deno task prepare
COPY . .
RUN deno task build

FROM caddy:2.10-alpine as runner
EXPOSE 3000
WORKDIR /srv
COPY --from=builder /app/build /srv

CMD ["caddy", "file-server", "--listen", "0.0.0.0:3000"]
HEALTHCHECK CMD wget -O /dev/null http://localhost:3000
