FROM node:lts-alpine AS builder
WORKDIR /app

EXPOSE 3000

CMD [ "sh", "-c", "npm install && npm run dev -- --host" ]

# Simplified healthcheck without curl
HEALTHCHECK CMD wget --quiet --tries=1 --spider http://localhost:3000 || exit 1