FROM denoland/deno:alpine AS builder
WORKDIR /app

COPY deno.json deno.lock* .
COPY svelte.config.js .
RUN deno install
RUN deno task prepare
COPY . .
RUN deno task build

FROM denoland/deno:alpine AS runner

WORKDIR /app

COPY --from=builder /app/deno.json .
COPY --from=builder /app/build/ build/

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "deno", "run", "-A", "build/" ]
