export VITE_API_BASE_EXTERNAL:= "http://localhost:5000"
export VITE_API_BASE_INTERNAL:= "http://localhost:5000"

help:
    just --list

deno +args:
	deno {{args}}

install:
	deno install --allow-scripts=npm:@tailwindcss/oxide@4.1.11

lint:
	deno task check

generate-api-types:
	deno task generate-api-types
