FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl build-essential
ENV FLASK_APP=src.app:create_app

CMD [ "uv", "run", "flask", "run", "--host=0.0.0.0", "--debug"]

HEALTHCHECK CMD curl -f -o /dev/null http://127.0.0.1:5000/api/openapi/openapi.json
