FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl build-essential
ENV FLASK_APP=src
ENV PYTHONPATH=/app

COPY pyproject.toml uv.lock .
RUN uv sync --locked

COPY . .

CMD [ "uv","run", "waitress-serve", "--host", "0.0.0.0", "--port", "5000", "--call", "src.app:create_app" ]

HEALTHCHECK CMD curl -f -o /dev/null http://localhost:5000/api/openapi/openapi.json
