FROM python:3.13-slim
ENV FLASK_APP=src

WORKDIR /app

RUN pip install waitress

COPY pyproject.toml .
RUN pip install .

COPY . .

CMD [ "waitress-serve", "--host", "0.0.0.0", "--port", "5000", "--call", "src.app:create_app" ]

HEALTHCHECK CMD curl -o /dev/null http://localhost:5000/openapi/openapi.json
