FROM ghcr.io/astral-sh/uv:python3.13-alpine
WORKDIR /app
RUN apk add --no-cache curl

RUN uv pip install ipython

COPY pyproject.toml uv.lock .
RUN uv sync --locked

ENV FLASK_APP=src.app:create_app

CMD [ "uv", "python", "-m" , "flask", "run", "--host=0.0.0.0", "--debug"]

HEALTHCHECK CMD curl -f -o /dev/null http://localhost:5000/api/openapi/openapi.json
