help:
    just --list

lint:
    uv run ruff check src
    uv run mypy src

format:
    uv run ruff format

test *args:
    uv run pytest --last-failed {{args}}

watch-test:
    git ls-files | entr -c just test

ci report_output="pytest-report.md":
    just --justfile ../justfile _docker-compose-prod up --build -d --wait backend
    just test -v --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed --md-report-output {{report_output}}

jupyter:
    uv run marimo edit ./probe_etoro.py
