name: 'finance-dashboard-dev'
services:
  backend:
    image: gitea.eldolfin.top/eldolfin/finance-plots-backend-dev:latest
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend/src:/app/src
  frontend:
    image: gitea.eldolfin.top/eldolfin/finance-plots-frontend-dev:latest
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src:ro
