help:
    just --list

# Restart frontend & backend with a clean DB
test-prepare:
    docker compose -f ../dev/docker-compose.yml -f docker-compose.yml down
    docker volume rm wsb-test-backend-db || true
    docker volume create wsb-test-backend-db
    docker compose -f ../dev/docker-compose.yml -f docker-compose.yml up -d --build

# Restarts frontend & backend with a clean DB then runs tests
run: test-prepare _test
_test:
    npx playwright test

# Same as `test` but with the --ui argument passed to playwright for debugging
run-ui: test-prepare
    npx playwright test --ui

# watch tests files only, and keep the same running backend instance
watch-tests:
    git ls-files | entr -cr just _test

# watch all repository files, and runs tests from a clean state
watch-all:
    cd .. && git ls-files | entr -cr just tests test
    
# Ran by github actions
ci: run
