[package]
name = "data-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
csv = "1.3.1"
serde = "1.0.219"
yahoo_finance_api = { version = "4.1.0", features = ["blocking"] }
