name: Lint Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - uses: taiki-e/install-action@just
    - name: Setup environment
      run: cp .env.example .env
    - name: Run backend lint
      run: just backend lint

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: taiki-e/install-action@just
    - name: Install frontend dependencies
      run: cd frontend && npm ci
    - name: Run frontend lint
      run: just frontend lint