name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: taiki-e/install-action@just
    - name: Install tests dependencies
      run: cd tests && npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Setup environement
      run: cp .env.example .env
    - name: Run Playwright tests
      run: just tests ci
    - name: Show logs on failure
      if: failure()
      run: docker compose -f dev/docker-compose.yml logs
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
